### ISSUE TITLE
DOM based XSS on jindo.dev.naver.com

### ISSUE THREAD

**Issue by mala** [naver/jindojs-jindo#16]
http://jindo.dev.naver.com/docs/jindo/2.12.1/desktop/en/classes/jindo.html#<img src=x onerror=alert(1)>

http://jindo.dev.naver.com/docs/jindo/2.12.1/desktop/en/assets/api-list.js
https://github.com/naver/jindojs-jindo/blob/master/build/api/theme/assets/api-list.js#L16-L18

http://jindo.dev.naver.com/docs/jindo/2.12.1/desktop/en/classes/jindo.$Element.html#constructor_jindo.%24Element

**Comment by mala** [comment]
ping @netil

**Comment by netil** [comment]
Thanks @mala for your report.
issue will be fixed ASAP.

**Comment by Minsik-Ahn** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
안민식(minsik.ahn@worksmobi...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [jindojs-jindo] DOM based XSS on jindo.dev.naver.com (#16)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
안민식(minsik.ahn@worksmobi...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-08-21 00:00 ~ 2015-08-24 23:59 GMT +09:00]<br>안녕하세요.<br>8/21 ~ 24일 여름 휴가로 부재중입니다.<br>급한 용무가 있으시면 메신저 주세요. 확인하는대로 답변드리겠습니다.
--------------------------------------------

**Comment by mala** [comment]
why not deployed?
```
http://jindo.dev.naver.com/docs/jindo/2.12.1/desktop/en/classes/jindo.html#<img src=x onerror=alert(1)>
http://jindo.dev.naver.com/docs/jindo/2.12.2/desktop/en/classes/jindo.html#<img src=x onerror=alert(1)>
```

**Comment by netil** [comment]
@mala there was some inconvenience on deploying. Has been deployed for every version doc.
