### ISSUE TITLE
m.CubeReveal shows slides effect when closed on Galaxy S7 SBrowser.

### ISSUE THREAD

**Issue by jongmoon** [naver/jindojs-jindo#23]
m.CubeReveal shows slides effect when closed on Galaxy S7 SBrowser

## Description

On Galaxy S7 SBrowser

**Result**
![cubereveal-slide](https://cloud.githubusercontent.com/assets/3255471/13945125/32519e6c-f04e-11e5-81c6-ccbd1c998793.gif)

**Expected**
![cubereveal-cube](https://cloud.githubusercontent.com/assets/3255471/13945215/df76c6c6-f04e-11e5-8ce6-df40a8159ca2.gif)

## Steps to check or reproduce

1. http://jindo.nhncorp.com/docs/jindo-mobile/archive/1.17.1/demo/jindo.m.CubeReveal/3.%20leftCube.html
2. Click 'Hamburger' button --> Show menu
3. Click 'Hamburger' button --> Hide menu

It reproduce on step3

**Comment by sculove** [comment]
I moved to jindojs-jmc https://github.com/naver/jindojs-jmc/issues/14
